### ISSUE TITLE
CRUD Registro de Talleres

### ISSUE THREAD

**Issue by LuisG-Custodio** [Tlacualli/PI_Tlacualli#23]
- [x] Alta de talleres
- [x] Edición y eliminación de publicación
- [x] Subir al menos una fotografía para el taller
- [ ] Localización de sitio para taller, utilizar API de Google Maps

**Es posible ocupar herramientas ya conocidas como SweetAlert para notificaciones, puede cambiar en el futuro
Utilizart Tailwinds para los estilos en caso de ser necesario**

**Comment by 4ngero** [comment]
Tengo una situación, ya que para integrar la parte de la ubicación del taller no tenemos un campo ni en formulario de registro de taller ni en base de datos. ¿Habrá que generar un nuevo campo? ¿O utilizo el de "notas" que ya tenemos para ingresar la ubicación?

**Comment by LuisG-Custodio** [comment]
Modifica la migración como consideres pertinente, igual puedes cambiar el de notas por el campo que te sea útil.

**Comment by LuisG-Custodio** [comment]
Ahorita el proyecto ya esta integrado con los módulos de usuario, solicitudes, productos y talleres, solo existe un problema por que aparentemente no almacena en la base de datos, de ahi en fuera, parece ser que las rutas trabajan bien, favor de revisarlo.

Hacer el rebase del main de favor
