### ISSUE TITLE
CRUD Publicaciones

### ISSUE THREAD

**Issue by LuisG-Custodio** [Tlacualli/PI_Tlacualli#24]
- [x] Subir publicación
- [x] Comenzar por subir y mostrar PDF
- [ ] Referencias de archivo
- [ ] Edición de titulo

**Es posible ocupar herramientas ya conocidas como SweetAlert para notificaciones, puede cambiar en el futuro
Utilizart Tailwinds para los estilos en caso de ser necesario**

**Comment by 4ngero** [comment]
¿A qué se refiere con lo de referencias de archivo? Entiendo que es una referencia tal cual pero como un enlace? Solo como un campo adicional de texto con la referencias o cómo está esta parte?

**Comment by 4ngero** [comment]
¿Solo se podrá editar el título? ¿Existen más campos de edición de la publicación?

**Comment by LuisG-Custodio** [comment]
Este issue quedará trunco para la version v2.3.2
