### ISSUE TITLE
CRUD Servicio

### ISSUE THREAD

**Issue by LuisG-Custodio** [Tlacualli/PI_Tlacualli#26]
- [x] Alta de Servicio
- [x] Edición y eliminación de Servicio
- [ ] Subir al menos una fotografía de area de servicio

**Es posible ocupar herramientas ya conocidas como SweetAlert para notificaciones, puede cambiar en el futuro
Utilizart Tailwinds para los estilos en caso de ser necesario**

**Comment by ISM42** [comment]
El único servicio detectado hasta ahora es la recolección de residuos. Habría que modificar la tabla de "solicitudes" para que no haya problema con el campo "id_publicación". 

En la tabla "tipo_solicitud" colocar "recolección" como primer registro para usarlo al llenar la tabla.

**Comment by ISM42** [comment]
DUDAS:
Para el formulario de servicios, no debería preguntarse el nombre del usuario que realiza la solicitud del servicio pues debería detectarlo automáticamente al haber iniciado sesión, por lo tanto, únicamente deberían darse a seleccionar el proveedor con quien desea solicitar el servicio, describir lo que requiere, seleccionar el tipo de publicación (servicio), el tipo de solicitud (servicio) y la fecha.

(Aún así suena a que sería redundante para el cliente seleccionar el tipo de publicación y el tipo de solicitud (cuando ya está dentro del apartado "servicios", además tampoco debería seleccionar el estatus), incluso para la tabla de usuarios, no debería llenar uno mismo el campo "estatus". Si estos campos no son tarea específica del usuario, ¿cómo hacer para que se llenen de forma automática?, ¿con un procedimiento almacenado?

¿El apartado de servicios podría tener su propia vista de "Mis servicios" para que puedan ser visualizados y gestionados por los usuarios (con sesión iniciada). En esta vista podría verse un historial de servicios solicitados. ¿Qué pasaría con los servicios que ya fueron resueltos? (se muestran en el historial con un estatus específico (finalizado, completado?) o simplemente no se mostrarían en el historial?

Si se cuenta con una vista donde se vean los servicios, cambiaría la vista de acuerdo al rol del usuario? (una vista donde el procesador de RO vea la lista de las solicitudes de recolección que tiene pendientes) y una vista para el usuario solicitante donde vea el historial de solicitudes en curso? o lo mejor sería únicamente enviar un correo electrónico al recolector sobre la solicitud hecha y un correo de copia para el usuario solicitante? (probablemente, en cualquiera de ambos casos, el correo puede servir como notificación).

Si se requiere agregar una imagen o una ubicación, esta cuestión cómo se manejaría en la BD? Se tendría que modificar la BD para agregar una imagen (RUTA) o si fuera sólo un mapa, ¿qué pasa?

**Comment by LuisG-Custodio** [comment]
Para el día de la carga, se realizaron modificaciones menores, pero el funcionamiento básico ya se encuentra presente, se podran agregar funciones extra en posteriores versiones.

Para nuevas modificaciones, se creará un nuevo issue
