### ISSUE TITLE
Estilos formularios

### ISSUE THREAD

**Issue by ISM42** [Tlacualli/PI_Tlacualli#47]
Pasar a TailwindCSS los estilos de los formularios junto con sus botones.

Incluye mensajes de validación (campos vacíos).

NOTA: hacer pull request a la rama FRONT_MAIN.

**Comment by ISM42** [comment]
-Los formularios incluyen los de inserts (crear), actualizar y eliminar de talleres, productos y servicios.
-Pasar los formularios de creación, actualización y eliminación de servicios a modales.
-El módulo de servicios (consultas) seguirá trabajando con tabla (sólo se sustituyen estilos de Bootstrap a TailwindCSS).

NOTA: no tocar los CARDS.
NOTA2: aún no se trabaja en esta parte los mensajes de alerta (éxito o error).

**Comment by ISM42** [comment]
25.07.24
                       LISTA DE ESTILOS TERMINADOS
-Tabla para consultar las solicitudes registradas.
-Barra de búsqueda en vista "mis_servicios".
-Estilo de botones.
-Modal "Nueva Solicitud.
-Mensajes de validación en modal "Nueva Solicitud" (recuadro gris con texto blanco).

                      PENDIENTES
-Integración de modales "editar" y "eliminar".
-Integración de estilos en los modales de talleres, publicaciones y productos, inicio de sesión.

**Comment by LuisG-Custodio** [comment]
Se agregaron exitosamente los estilos a los formularios del proyecto, hasta la versión v2.2.0
