### ISSUE TITLE
Estilos mensajes de éxito o error

### ISSUE THREAD

**Issue by ISM42** [Tlacualli/PI_Tlacualli#50]
Definir un estilo unificado para los mensajes de éxito o error al crear, editar o eliminar un registro.

¿Un estilo distinto para el mensaje de éxito o error para el inicio de sesión?

*En este Issue debe decidirse si se trabajará con JS, CSS, o algún estilo creado con clases Tailwind, para reemplazar aquellos de SweetAlert, JS (sin estilos) y Bootstrap.

**Comment by LuisG-Custodio** [comment]
Por la naturaleza de este, el mensaje de error o éxito sera distinto para login, deja busco otra librería y veo que pudiera ocuparse
